
- name: Configuration des interfaces sur un routeur Cisco CSR
  hosts: csr1000
  gather_facts: false

  tasks:
    - name: Configurer l'interface GigabitEthernet1
      cisco.ios.ios_l3_interfaces:
        config:
        - name: GigabitEthernet1
          ipv4:
            - dhcp:
               enable: true

        - name: GigabitEthernet2
          ipv4:
          - address: 192.168.2.1/24

        - name: GigabitEthernet3          
          ipv4:
          - address: 192.168.3.1/24


        - name: GigabitEthernet4
          ipv4:
          - address: 192.168.4.1/24
        state: merged



  tasks:
    - name: Configurer l'interface GigabitEthernet1
      cisco.ios.ios_interfaces:
        config:
        - name: GigabitEthernet1
          description: Interface G1
          enabled: true

        - name: GigabitEthernet2
          description: Interface G2
          enabled: true


        - name: GigabitEthernet3
          description: Interface G3
          enabled: true


        - name: GigabitEthernet4
          description: Interface G4
          enabled: true
        state: merged
