- name: Acte1 - essai csr1000
  hosts: csr1000
  gather_facts: false

  tasks:
    - name: recupere la config
      cisco.ios.ios_command:
        commands: show running-config
      register: config
   
    - name: enregistre la config
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "show_run_{{ inventory_hostname }}.txt"
